import fs from "node:fs";
import path from "node:path";
const root=process.cwd(),output=path.resolve(root,process.argv[2]||"_site");const adoption=JSON.parse(fs.readFileSync(path.join(root,".arwp/adoption.json"),"utf8"));const source=path.resolve(root,adoption.profile_source);if(!source.startsWith(root+path.sep))throw new Error("Profile source must remain inside this repository");const profile=JSON.parse(fs.readFileSync(source,"utf8"));if(profile.profileVersion!=="0.1"||profile.canonicalUrl!==adoption.site_url)throw new Error("Profile and adoption identity differ");const homepage=path.join(output,"index.html"),destination=path.join(output,"ai/site-profile.json");if(!fs.existsSync(homepage))throw new Error(`Build the public homepage first: ${homepage}`);fs.mkdirSync(path.dirname(destination),{recursive:true});if(source!==destination)fs.copyFileSync(source,destination);const href=new URL("ai/site-profile.json",profile.canonicalUrl).href;let html=fs.readFileSync(homepage,"utf8");const link=`<link id="arwp-profile-discovery" rel="describedby" type="application/json" href="${href}" title="Agent-Ready Web Profile">`;html=html.includes('id="arwp-profile-discovery"')?html.replace(/<link\s[^>]*id="arwp-profile-discovery"[^>]*>/i,link):html.replace(/<\/head>/i,`${link}\n</head>`);const title=html.match(/<title>([^<]+)<\/title>/i)?.[1]?.trim(),description=html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["'][^>]*>/i)?.[1]?.trim(),canonical=html.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["'][^>]*>/i)?.[1]?.trim();if(!title||!description||canonical!==profile.canonicalUrl)throw new Error("Homepage Search identity is incomplete or canonical differs from ARWP");const u=new URL(profile.canonicalUrl),hostName=u.pathname==="/"?profile.name:(u.hostname==="dkharlanau.github.io"?"Dzmitryi Kharlanau":profile.name),esc=v=>String(v).replaceAll("&","&amp;").replaceAll('"',"&quot;");const meta=(a,k,v)=>{const p=new RegExp(`<meta\\s+${a}=["']${k}["'][^>]*>`,`i`),t=`<meta ${a}="${k}" content="${esc(v)}" data-arwp-search-appearance="true">`;html=p.test(html)?html.replace(p,t):html.replace(/<\/head>/i,`${t}\n</head>`)};meta("property","og:site_name",hostName);meta("property","og:title",title);meta("property","og:description",description);meta("property","og:url",canonical);meta("name","twitter:title",title);meta("name","twitter:description",description);html=html.replace(/<\/head>/i,'<link rel="icon" type="image/png" sizes="192x192" href="https://dkharlanau.github.io/assets/favicons/icon-192.png" data-arwp-search-appearance="true">\n</head>');fs.writeFileSync(homepage,html);if((html.match(/data-arwp-search-appearance="true"/g)||[]).length<7)throw new Error("Search appearance staging incomplete");console.log(`ARWP staged; search-identity=${hostName}`);

// Goose ARWP Proof Mark fleet dogfood. Repository evidence exists; whole-site audit coverage is not yet claimed.
{
  const proofProduct="https://dkharlanau.github.io/agent-ready-web-profile/product/";
  const proofContract="https://github.com/dkharlanau/agent-ready-web-profile/blob/main/docs/PROOF-MARK.md";
  let proofHtml=fs.readFileSync(homepage,"utf8");
  if(!proofHtml.includes('data-goose-arwp-proof-mark="0.1"')){
    const proofMark=`<span data-goose-arwp-proof-mark="0.1" data-arwp-coverage="partial" role="group" aria-label="Goose ARWP Proof Mark: partial audit scope" title="Repository-level ARWP evidence is present; whole-site audit scope remains incomplete." style="display:inline-flex;max-width:100%;min-height:38px;border:1px solid #080c0b;border-radius:4px;overflow:hidden;background:#fafaf7;color:#080c0b;font:10px/1.15 Arial,sans-serif;vertical-align:middle"><a href="${proofProduct}" aria-label="Open Goose ARWP" style="display:flex;flex-direction:column;justify-content:center;padding:6px 9px;background:#080c0b;color:#fafaf7;text-decoration:none;border-right:4px solid #173bea;font-weight:700;letter-spacing:.06em">GOOSE ARWP<small style="margin-top:3px;font:7px/1.1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:0">PROOF MARK v0.1</small></a><a href="${proofContract}" aria-label="Read Proof Mark contract: partial scope" style="display:flex;flex-direction:column;justify-content:center;padding:6px 9px;color:#080c0b;text-decoration:none"><strong style="font-size:10px">PARTIAL</strong><small style="margin-top:3px;font:8px/1.1 ui-monospace,SFMono-Regular,Menlo,monospace">scope incomplete</small></a></span>`;
    const block=`<span data-goose-arwp-proof-mark-slot="footer" style="display:block;margin-top:12px">${proofMark}</span>`;
    if(/<\/footer>/i.test(proofHtml)) proofHtml=proofHtml.replace(/<\/footer>/i,`${block}</footer>`);
    else if(/<\/body>/i.test(proofHtml)) proofHtml=proofHtml.replace(/<\/body>/i,`<footer aria-label="Site quality evidence" style="padding:20px">${block}</footer></body>`);
    else throw new Error("Public homepage has no footer or closing body for Goose ARWP Proof Mark");
    fs.writeFileSync(homepage,proofHtml);
  }
}
